version: 2.1  # Adjust if needed based on CircleCI version

jobs:
  run-virta-assignment:
    docker:
      - image: circleci/node:lts  # Use a Node.js image with LTS version
    steps:
      - checkout #code fetch from the git current branch
      - name: Install typescript globally
        run: npm intall -g typescript 
      - name: Compile virtaAssignment.ts
        run: tsc --target esnext virtaAssignment.ts  # Compile only the virtaAssignment.ts file
      - name: Run virtaAssignment.js
        run: node virtaAssignment.js  
workflows:
  build-and-test:  # You can rename this workflow section if needed
    jobs:
      - run-virta-assignment